apiVersion: apps/v1
kind: Deployment
metadata:
  name: workprofile
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workprofile
  template:
    metadata:
      labels:
        app: workprofile
    spec:
      containers:
      - name: workprofile
        image: ghcr.io/YOUR_GITHUB_USERNAME/workprofile:latest
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secret
