apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk      # rootpassword (base64 encoded)
  MYSQL_USER: Zmxhc2thcHA=                  # flaskapp
  MYSQL_PASSWORD: Zmxhc2thcHA=              # flaskapp
  MYSQL_DATABASE: ZXhhbXBsZURi              # exampleDb
