apiVersion: v1
kind: Service
metadata:
  name: workprofile
spec:
  type: NodePort
  selector:
    app: workprofile
  ports:
    - port: 5000        # הפורט שבו ניגשים לשירות
      targetPort: 5000  # הפורט שבו האפליקציה מאזינה בפוד
      nodePort: 30080   # הפורט שייפתח מבחוץ על ה-Node
