version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: wp-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - workprofile

  workprofile:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: wp-app
    environment:
      DB_HOST: mysql
      DB_USER: flaskapp
      DB_PASS: flaskapp
      DB_NAME: exampleDb
    ports:
      - "5000:5000"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: wp-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: exampleDb
      MYSQL_USER: flaskapp
      MYSQL_PASSWORD: flaskapp
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
