name: CI/CD Demo CRM

on:
  push:
    branches:
      - main

env:
  IMAGE_TAG: 1.0.${{ github.run_number }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # שלב 1: קוד
      - name: Checkout source code
        uses: actions/checkout@v3

      # שלב 2: Build & Push
      - name: Build and push Docker image
        run: |
          echo "Building Docker image..."
          docker build -t esti563/workprofile:${{ env.IMAGE_TAG }} .
          echo "Pushing Docker image to Docker Hub..."
          echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
          docker push esti563/workprofile:${{ env.IMAGE_TAG }}

      # שלב 3: Cluster
      - name: Set up kind cluster
        uses: helm/kind-action@v1.8.0
        with:
          cluster_name: kind
          wait: 300s

      # שלב 4: MySQL
      - name: Deploy MySQL
        run: |
          echo "Enabling default StorageClass..."
          kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/kind/main/examples/storageclass/default-storageclass.yaml
          echo "Deploying MySQL..."
          kubectl apply -f k8s/mysql-secret.yaml
          kubectl apply -f k8s/mysql-statefulset.yaml
          kubectl apply -f k8s/mysql-service.yaml
          echo "Waiting for MySQL to be ready..."
          kubectl wait --for=condition=ready pod/mysql-0 --timeout=600s || \
            (kubectl describe pod/mysql-0 && kubectl logs mysql-0 && exit 1)

      # שלב 5: App
      - name: Deploy WorkProfile app
        run: |
          echo "Loading app image into kind..."
          docker pull esti563/workprofile:${{ env.IMAGE_TAG }}
          kind load docker-image esti563/workprofile:${{ env.IMAGE_TAG }}
          echo "Deploying app..."
          kubectl apply -f k8s/workprofile-deployment.yaml
          kubectl apply -f k8s/workprofile-service.yaml
          echo "Waiting for app deployment..."
          kubectl wait --for=condition=available deployment/workprofile --timeout=600s || \
            (kubectl describe deployment/workprofile && exit 1)

      # שלב 6: Verify
      - name: Verify Deployment
        run: |
          echo "Getting all resources..."
          kubectl get all
          echo "Describing WorkProfile service..."
          kubectl describe service workprofile
