name: WorkProfile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/workprofile:latest .

    - name: Run healthcheck
      run: |
        docker run -d -p 5000:5000 --name testcontainer ${{ secrets.DOCKER_USERNAME }}/workprofile:latest
        sleep 10
        curl --fail http://localhost:5000/health
        echo "✅ Healthcheck passed!"
        docker stop testcontainer
        docker rm testcontainer

    - name: Push to DockerHub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/workprofile:latest

  e2e-test:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
    - name: Pull from DockerHub
      run: docker pull ${{ secrets.DOCKER_USERNAME }}/workprofile:latest

    - name: Run container from DockerHub
      run: |
        docker run -d -p 8080:5000 --name e2econtainer ${{ secrets.DOCKER_USERNAME }}/workprofile:latest
        sleep 10
        curl --fail http://localhost:8080/health
        echo "✅ E2E Test passed!"
        docker stop e2econtainer
        docker rm e2econtainer
